import { App, Plugin, setIcon, TFile } from 'obsidian';
import { getAllDailyNotes, getDailyNote, getDateFromFile } from 'obsidian-daily-notes-interface';
import { CrystalPluginSettings } from './settings';
const moment = require('moment');

// Gamification: reward completing daily-note tasks (e.g. those generated by the
// Silhouette plugin) with XP, levels and streaks, using variable rewards so the
// payoff isn't predictable. See docs for the psychology behind this design:
// dopamine peaks at *anticipation*, not at the reward itself, and unpredictable
// (variable-ratio) rewards sustain engagement far better than fixed ones.

export type RewardTier = 'normal' | 'bonus' | 'rare';

export interface Reward {
    xp: number;
    tier: RewardTier;
}

export interface LevelInfo {
    level: number;
    xpIntoLevel: number;
    xpForNextLevel: number;
}

const BASE_XP = 10;
const BONUS_XP = 20;
const RARE_XP = 50;
const RARE_CHANCE = 0.03;
const BONUS_CHANCE = 0.15;

/** XP required to advance from `level` to `level + 1`. */
function xpForLevel(level: number): number {
    return level * 100;
}

/**
 * Derive the current level and progress within it from total accumulated XP.
 */
export function calculateLevel(totalXP: number): LevelInfo {
    let level = 1;
    let consumed = 0;
    let needed = xpForLevel(level);
    while (totalXP - consumed >= needed) {
        consumed += needed;
        level += 1;
        needed = xpForLevel(level);
    }
    return { level, xpIntoLevel: totalXP - consumed, xpForNextLevel: needed };
}

/**
 * Roll a variable reward for a single completed task. `random` is injectable for tests.
 */
export function rollReward(random: () => number = Math.random): Reward {
    const roll = random();
    if (roll < RARE_CHANCE) {
        return { xp: RARE_XP, tier: 'rare' };
    }
    if (roll < RARE_CHANCE + BONUS_CHANCE) {
        return { xp: BONUS_XP, tier: 'bonus' };
    }
    return { xp: BASE_XP, tier: 'normal' };
}

/**
 * Strip fenced code blocks (``` or ~~~, including indented ones) before
 * scanning for checkboxes, so a note that *documents* task syntax (e.g.
 * explaining the Tasks plugin) inside a code sample isn't counted as real
 * tasks.
 */
function stripCodeBlocks(content: string): string {
    return content.replace(/^[ \t]*(`{3,}|~{3,})[^\n]*\n[\s\S]*?^[ \t]*\1[ \t]*$/gm, '');
}

/** Count completed checkbox tasks (`- [x]`) in note content. */
export function countCompletedTasks(content: string): number {
    const matches = stripCodeBlocks(content).match(/^[ \t]*(?:[-*+]|\d+[.)])[ \t]+\[[xX]\]/gm);
    return matches ? matches.length : 0;
}

/** Count all checkbox tasks (any state: `- [ ]`, `- [x]`, `- [/]`, etc.) in note content. */
export function countTotalTasks(content: string): number {
    const matches = stripCodeBlocks(content).match(/^[ \t]*(?:[-*+]|\d+[.)])[ \t]+\[.\]/gm);
    return matches ? matches.length : 0;
}

function daysBetween(from: string, to: string): number {
    const msPerDay = 24 * 60 * 60 * 1000;
    const a = new Date(`${from}T00:00:00Z`).getTime();
    const b = new Date(`${to}T00:00:00Z`).getTime();
    return Math.round((b - a) / msPerDay);
}

/**
 * Compute the streak after a task completion on `activeDate` (YYYY-MM-DD).
 * - Same date as last time: streak unchanged (already counted today).
 * - Exactly one day after last time: streak extends.
 * - Otherwise (gap, or first ever completion): streak resets to 1.
 */
export function nextStreak(previousDate: string | null, currentStreak: number, activeDate: string): number {
    if (previousDate === activeDate) return currentStreak;
    if (previousDate && daysBetween(previousDate, activeDate) === 1) {
        return currentStreak + 1;
    }
    return 1;
}

export interface StreakResult {
    streak: number;
    freezeTokensUsed: number;
}

/**
 * Count the days strictly between `previousDate` and `activeDate` that are
 * *not* one of `restDays` (local day-of-week numbers, 0=Sunday..6=Saturday).
 * Used so a configured weekly rest day never counts as a "missed" day.
 */
export function countNonRestMissedDays(previousDate: string, activeDate: string, restDays: number[]): number {
    const msPerDay = 24 * 60 * 60 * 1000;
    const start = new Date(`${previousDate}T00:00:00Z`).getTime();
    const end = new Date(`${activeDate}T00:00:00Z`).getTime();
    let missed = 0;
    for (let t = start + msPerDay; t < end; t += msPerDay) {
        if (!restDays.includes(new Date(t).getUTCDay())) missed++;
    }
    return missed;
}

/**
 * Like `nextStreak`, but a gap of missed days can be bridged with freeze
 * tokens (one token per missed day) instead of resetting the streak. Used to
 * avoid the "missed one day, streak gone, why bother" drop-off. Days listed
 * in `restDays` (local day-of-week, 0=Sunday..6=Saturday) never count as
 * missed and never cost a freeze token — a deliberate day off each week.
 */
export function nextStreakWithFreeze(
    previousDate: string | null,
    currentStreak: number,
    activeDate: string,
    freezeTokensAvailable: number,
    restDays: number[] = []
): StreakResult {
    if (previousDate === activeDate) return { streak: currentStreak, freezeTokensUsed: 0 };
    if (!previousDate) return { streak: 1, freezeTokensUsed: 0 };

    const gap = daysBetween(previousDate, activeDate);
    if (gap === 1) return { streak: currentStreak + 1, freezeTokensUsed: 0 };
    if (gap > 1) {
        const missedDays = restDays.length > 0 ? countNonRestMissedDays(previousDate, activeDate, restDays) : gap - 1;
        if (missedDays === 0) return { streak: currentStreak + 1, freezeTokensUsed: 0 };
        if (freezeTokensAvailable >= missedDays) {
            return { streak: currentStreak + 1, freezeTokensUsed: missedDays };
        }
    }
    return { streak: 1, freezeTokensUsed: 0 };
}

const FREEZE_TOKENS_PER_MONTH = 2;

/**
 * Refill freeze tokens to a flat amount at the start of each calendar month.
 * Pure function: "current month" is whatever `referenceDate` says it is —
 * callers should pass the real current date, not a possibly-backdated note's
 * date, so a backfilled old note can't shift the refill month. Tokens don't
 * accumulate across months.
 */
export function refillFreezeTokens(
    currentTokens: number,
    lastRefillMonth: string,
    referenceDate: string,
    tokensPerMonth: number = FREEZE_TOKENS_PER_MONTH
): { tokens: number; refillMonth: string } {
    const month = referenceDate.slice(0, 7); // YYYY-MM
    if (month !== lastRefillMonth) {
        return { tokens: tokensPerMonth, refillMonth: month };
    }
    return { tokens: currentTokens, refillMonth: lastRefillMonth };
}

export interface Badge {
    id: string;
    name: string;
    description: string;
    /** Lucide icon name (see obsidian's `setIcon`), not an emoji — kept crisp and theme-aware. */
    icon: string;
    /** Hidden badges show no hint (not even the requirement) until unlocked — a surprise to discover. */
    hidden?: boolean;
}

type BadgeMetric = 'level' | 'streak';

interface BadgeRule extends Badge {
    metric: BadgeMetric;
    threshold: number;
}

const LEVEL_BADGES: BadgeRule[] = [
    { id: 'level-5', name: 'Rookie', description: 'Reach level 5', icon: 'award', metric: 'level', threshold: 5 },
    { id: 'level-10', name: 'Adept', description: 'Reach level 10', icon: 'shield', metric: 'level', threshold: 10 },
    { id: 'level-20', name: 'Veteran', description: 'Reach level 20', icon: 'medal', metric: 'level', threshold: 20 },
    { id: 'level-30', name: 'Master', description: 'Reach level 30', icon: 'gem', metric: 'level', threshold: 30 },
    { id: 'level-50', name: 'Legend', description: 'Reach level 50', icon: 'crown', metric: 'level', threshold: 50 },
];

/**
 * The level-badge names double as level "titles" — reused here as a compact
 * one-line status (e.g. "LEVEL 12 · Adept") instead of only living inside the
 * badge collection.
 */
export function titleForLevel(level: number): string {
    let title = 'Beginner';
    for (const badge of LEVEL_BADGES) {
        if (level >= badge.threshold) title = badge.name;
    }
    return title;
}

const STREAK_BADGES: BadgeRule[] = [
    { id: 'streak-3', name: 'Firestarter', description: '3-day streak', icon: 'flame', metric: 'streak', threshold: 3 },
    { id: 'streak-7', name: 'Week Streak', description: '7-day streak', icon: 'flame', metric: 'streak', threshold: 7 },
    { id: 'streak-30', name: 'Habit Master', description: '30-day streak', icon: 'flame', metric: 'streak', threshold: 30 },
    { id: 'streak-100', name: 'Centurion', description: '100-day streak', icon: 'flame', metric: 'streak', threshold: 100 },
];

/** Secret badges with unusual, non-metric conditions — discovered by surprise, not chased. */
export const SPECIAL_BADGE_IDS = {
    NIGHT_OWL: 'special-night-owl',
    TEN_IN_A_DAY: 'special-ten-in-a-day',
} as const;

const NIGHT_OWL_BADGE: Badge = { id: SPECIAL_BADGE_IDS.NIGHT_OWL, name: 'Night Owl', description: 'Complete a task between midnight and 5am', icon: 'moon', hidden: true };
const TEN_IN_A_DAY_BADGE: Badge = { id: SPECIAL_BADGE_IDS.TEN_IN_A_DAY, name: 'Overdrive', description: 'Complete 10+ tasks in a single day', icon: 'rocket', hidden: true };

const SPECIAL_BADGES: Badge[] = [NIGHT_OWL_BADGE, TEN_IN_A_DAY_BADGE];

/**
 * Check the hidden/special badges, which don't fit the level/streak metric
 * system. `hour` is the local hour (0-23) the completion happened at.
 */
export function checkNewlySpecialUnlocks(
    context: { hour: number; todayTaskCount: number },
    unlockedIds: string[]
): Badge[] {
    const unlocked: Badge[] = [];
    if (!unlockedIds.includes(SPECIAL_BADGE_IDS.NIGHT_OWL) && context.hour >= 0 && context.hour < 5) {
        unlocked.push(NIGHT_OWL_BADGE);
    }
    if (!unlockedIds.includes(SPECIAL_BADGE_IDS.TEN_IN_A_DAY) && context.todayTaskCount >= 10) {
        unlocked.push(TEN_IN_A_DAY_BADGE);
    }
    return unlocked;
}

const ALL_BADGE_RULES: BadgeRule[] = [...LEVEL_BADGES, ...STREAK_BADGES];

export const ALL_BADGES: Badge[] = [...ALL_BADGE_RULES, ...SPECIAL_BADGES];

function badgeMetricValue(badge: BadgeRule, state: { level: number; streak: number }): number {
    return badge.metric === 'level' ? state.level : state.streak;
}

/**
 * Return badges that newly satisfy their unlock condition and aren't
 * already in `unlockedIds`, in badge-list order.
 */
export function checkNewlyUnlockedBadges(
    state: { level: number; streak: number; totalXP: number },
    unlockedIds: string[]
): Badge[] {
    return ALL_BADGE_RULES.filter(
        (badge) => !unlockedIds.includes(badge.id) && badgeMetricValue(badge, state) >= badge.threshold
    );
}

export interface NearestBadgeTarget {
    badge: Badge;
    remaining: number;
    metric: BadgeMetric;
}

/**
 * Find the closest not-yet-unlocked badge, i.e. the one requiring the
 * smallest further progress on its metric. Surfaces a concrete next target
 * ("2 more levels to Adept") — visualizing the anticipation, not just the payoff.
 */
export function findNearestBadgeTarget(
    state: { level: number; streak: number },
    unlockedIds: string[]
): NearestBadgeTarget | null {
    let best: NearestBadgeTarget | null = null;
    for (const badge of ALL_BADGE_RULES) {
        if (unlockedIds.includes(badge.id)) continue;
        const remaining = badge.threshold - badgeMetricValue(badge, state);
        if (remaining <= 0) continue;
        if (!best || remaining < best.remaining) {
            best = { badge: { id: badge.id, name: badge.name, description: badge.description, icon: badge.icon }, remaining, metric: badge.metric };
        }
    }
    return best;
}

export interface BadgeSnapshot extends Badge {
    unlocked: boolean;
}

export interface TodayProgress {
    completed: number;
    total: number;
}

export interface DailyXP {
    date: string;
    xp: number;
}

/**
 * Keep only entries within `keepDays` of `referenceDate` (inclusive), so the
 * log doesn't grow forever.
 */
export function pruneDailyXPLog(
    log: Record<string, number>,
    referenceDate: string,
    keepDays = 30
): Record<string, number> {
    const pruned: Record<string, number> = {};
    for (const [date, xp] of Object.entries(log)) {
        const gap = daysBetween(date, referenceDate);
        if (gap >= 0 && gap <= keepDays) {
            pruned[date] = xp;
        }
    }
    return pruned;
}

/** Build a fixed-length series of the last `days` days ending at `endDate`, filling gaps with 0. */
export function getWeeklyXPSeries(log: Record<string, number>, endDate: string, days = 7): DailyXP[] {
    const msPerDay = 24 * 60 * 60 * 1000;
    const end = new Date(`${endDate}T00:00:00Z`).getTime();
    const series: DailyXP[] = [];
    for (let i = days - 1; i >= 0; i--) {
        const date = new Date(end - i * msPerDay).toISOString().slice(0, 10);
        series.push({ date, xp: log[date] ?? 0 });
    }
    return series;
}

/** Sum of XP over the last `days` days ending at `endDate` — used for the "best week" personal record. */
export function sumRecentXP(log: Record<string, number>, endDate: string, days = 7): number {
    return getWeeklyXPSeries(log, endDate, days).reduce((sum, day) => sum + day.xp, 0);
}

/** Streak lengths that grant a one-off bonus freeze token, translating Duolingo's
 * milestone-tier freeze grants (e.g. Streak Society) into this single-player context. */
const FREEZE_MILESTONES = [30, 100, 365];

/** Milestones in `FREEZE_MILESTONES` that `streak` has newly reached and aren't in `granted` yet. */
export function checkNewlyReachedFreezeMilestones(streak: number, granted: number[]): number[] {
    return FREEZE_MILESTONES.filter((milestone) => streak >= milestone && !granted.includes(milestone));
}

export interface StreakAdvanceInput {
    /** The day the completed task belongs to (the daily note's date). */
    activeDate: string;
    /** The real current date — always used for the freeze-token refill, since
     * "this calendar month" is a real-time concept that shouldn't shift just
     * because an old note was edited. */
    today: string;
    previousActiveDate: string | null;
    currentStreak: number;
    freezeTokensAvailable: number;
    freezeTokensRefillMonth: string;
    bestStreak: number;
    freezeMilestonesGranted: number[];
    /** -1 for "no rest day configured", otherwise 0(Sun)-6(Sat). */
    restDayOfWeek: number;
}

export interface StreakAdvanceOutput {
    /** True when `activeDate` precedes `previousActiveDate` — a backfill of
     * an old, already-past daily note rather than today's real activity. */
    isBackdatedEdit: boolean;
    freezeTokensAvailable: number;
    freezeTokensRefillMonth: string;
    streak: number;
    lastActiveDate: string;
    freezeTokensUsed: number;
    isComeback: boolean;
    newBestStreak: boolean;
    bestStreak: number;
    newMilestones: number[];
}

/**
 * Pure core of the streak/freeze-token bookkeeping, kept separate from
 * `GamificationManager` so it's directly unit-testable without mocking the
 * Obsidian API. Refills freeze tokens against the real calendar month, then
 * — unless this is a backdated (backfilled) edit, in which case the streak
 * is left untouched entirely — advances the streak (bridging a gap with
 * freeze tokens/rest days if possible), tracks the best-ever streak, and
 * grants any newly-reached freeze-token milestones.
 */
export function resolveStreakAdvance(input: StreakAdvanceInput): StreakAdvanceOutput {
    const { tokens, refillMonth } = refillFreezeTokens(input.freezeTokensAvailable, input.freezeTokensRefillMonth, input.today);

    const isBackdatedEdit = input.previousActiveDate !== null && input.activeDate < input.previousActiveDate;
    if (isBackdatedEdit) {
        return {
            isBackdatedEdit: true,
            freezeTokensAvailable: tokens,
            freezeTokensRefillMonth: refillMonth,
            streak: input.currentStreak,
            lastActiveDate: input.previousActiveDate as string,
            freezeTokensUsed: 0,
            isComeback: false,
            newBestStreak: false,
            bestStreak: input.bestStreak,
            newMilestones: [],
        };
    }

    const restDays = input.restDayOfWeek < 0 ? [] : [input.restDayOfWeek];
    const { streak, freezeTokensUsed } = nextStreakWithFreeze(
        input.previousActiveDate,
        input.currentStreak,
        input.activeDate,
        tokens,
        restDays
    );

    // A "comeback": the streak genuinely reset (not bridged by a freeze token
    // or rest day) after having been meaningfully underway. Worth a softer
    // message than silence.
    const isComeback = streak === 1 && freezeTokensUsed === 0 && input.currentStreak > 1;
    const newBestStreak = streak > input.bestStreak;
    const newMilestones = checkNewlyReachedFreezeMilestones(streak, input.freezeMilestonesGranted);

    return {
        isBackdatedEdit: false,
        freezeTokensAvailable: tokens - freezeTokensUsed + newMilestones.length,
        freezeTokensRefillMonth: refillMonth,
        streak,
        lastActiveDate: input.activeDate,
        freezeTokensUsed,
        isComeback,
        newBestStreak,
        bestStreak: newBestStreak ? streak : input.bestStreak,
        newMilestones,
    };
}

export interface GamificationSnapshot {
    enabled: boolean;
    level: number;
    levelTitle: string;
    xpIntoLevel: number;
    xpForNextLevel: number;
    totalXP: number;
    streak: number;
    freezeTokensAvailable: number;
    badges: BadgeSnapshot[];
    todayProgress: TodayProgress | null;
    totalTasksCompleted: number;
    startDate: string | null;
    weeklyXP: DailyXP[];
    monthlyXP: DailyXP[];
    nearestBadge: NearestBadgeTarget | null;
    freezeTokenLog: string[];
    bestStreak: number;
    bestDayTasks: number;
    bestWeekXP: number;
}

interface StreakUpdateResult {
    newlyUnlocked: Badge[];
    newBestStreak: boolean;
    isComeback: boolean;
    freezeMilestoneBonus: number;
}

export const VIEW_TYPE_GAMIFICATION = 'crystal-gamification-view';

type PluginWithSettings = Plugin & { settings: CrystalPluginSettings; saveSettings(): Promise<void> };

export class GamificationManager {
    private app: App;
    private plugin: PluginWithSettings;
    private settings: CrystalPluginSettings;
    private random: () => number;
    private taskCounts: Map<string, number> = new Map();
    private taskTotals: Map<string, number> = new Map();
    private todayProgress: TodayProgress | null = null;
    private statusBarItem: HTMLElement | null = null;
    private flashTimeoutId: number | null = null;
    private saveDebounceId: number | null = null;
    private onStatusBarClick?: () => void;

    constructor(
        app: App,
        plugin: PluginWithSettings,
        settings: CrystalPluginSettings,
        random: () => number = Math.random,
        onStatusBarClick?: () => void
    ) {
        this.app = app;
        this.plugin = plugin;
        this.settings = settings;
        this.random = random;
        this.onStatusBarClick = onStatusBarClick;
    }

    updateSettings(settings: CrystalPluginSettings) {
        this.settings = settings;
        this.renderStatusBar();
        // e.g. the settings tab's "Reset progress" button changes the
        // underlying data — make sure an already-open sidebar reflects it.
        this.refreshViews();
    }

    onLoad() {
        this.statusBarItem = this.plugin.addStatusBarItem();
        this.statusBarItem.addClass('crystal-gamification-status');
        if (this.onStatusBarClick) {
            this.statusBarItem.addClass('mod-clickable');
            this.plugin.registerDomEvent(this.statusBarItem, 'click', () => this.onStatusBarClick?.());
        }
        this.renderStatusBar();

        this.plugin.registerEvent(
            this.app.vault.on('modify', (file) => {
                if (file instanceof TFile) {
                    this.handleFileModify(file).catch((error) => {
                        console.error('Crystal gamification: failed to process file modification', error);
                    });
                }
            })
        );

        this.plugin.registerEvent(
            this.app.workspace.on('file-open', (file) => {
                if (file instanceof TFile) {
                    this.cacheBaseline(file).catch((error) => {
                        console.error('Crystal gamification: failed to cache baseline', error);
                    });
                }
            })
        );

        this.cacheTodayBaseline();
    }

    private isDailyNote(file: TFile): boolean {
        return getDateFromFile(file, 'day') !== null;
    }

    /**
     * Record a file's current completed-task count without granting any reward.
     * Used so we never retroactively reward tasks that were already checked
     * before the plugin observed the file.
     */
    private async cacheBaseline(file: TFile) {
        if (!this.isDailyNote(file)) return;
        if (this.taskCounts.has(file.path)) return;
        const content = await this.app.vault.cachedRead(file);
        // Re-check after the await: handleFileModify may have raced ahead and
        // already established a (more current) baseline for this file while
        // we were reading it. Don't clobber it with a possibly-stale read.
        if (this.taskCounts.has(file.path)) return;
        this.taskCounts.set(file.path, countCompletedTasks(content));
        this.taskTotals.set(file.path, countTotalTasks(content));
        this.refreshTodayProgress(file, content);
    }

    /** Update the cached today-progress snapshot if `file` is today's daily note. */
    private refreshTodayProgress(file: TFile, content: string) {
        const date = getDateFromFile(file, 'day');
        if (!date || date.format('YYYY-MM-DD') !== moment().format('YYYY-MM-DD')) return;
        this.todayProgress = { completed: countCompletedTasks(content), total: countTotalTasks(content) };
    }

    private cacheTodayBaseline() {
        try {
            const allNotes = getAllDailyNotes();
            const today = getDailyNote(moment(), allNotes);
            if (today) {
                this.cacheBaseline(today).catch((error) => {
                    console.error('Crystal gamification: failed to cache today baseline', error);
                });
            }
        } catch (error) {
            // Daily notes folder/settings not available yet; nothing to prime.
        }
    }

    private async handleFileModify(file: TFile) {
        if (!this.settings.gamificationEnabled || !this.isDailyNote(file)) return;

        const date = getDateFromFile(file, 'day');
        const content = await this.app.vault.cachedRead(file);

        const newCount = countCompletedTasks(content);
        const newTotal = countTotalTasks(content);
        const prevCount = this.taskCounts.get(file.path);
        const prevTotal = this.taskTotals.get(file.path);
        this.taskCounts.set(file.path, newCount);
        this.taskTotals.set(file.path, newTotal);

        // First time we see this file: only establish the baseline, still refresh the view.
        if (prevCount === undefined || !date) {
            this.refreshTodayProgress(file, content);
            this.refreshViews();
            return;
        }

        const delta = newCount - prevCount;
        if (delta <= 0) {
            // No new completion (e.g. a task was unchecked, or a non-task edit).
            // Only touch the view if something task-related actually changed —
            // an unrelated prose edit shouldn't tear down and rebuild the whole
            // panel (that was destroying badge tooltips mid-hover).
            if (newCount !== prevCount || newTotal !== prevTotal) {
                this.refreshTodayProgress(file, content);
                this.refreshViews();
            }
            return;
        }

        this.refreshTodayProgress(file, content);

        const dateStr = date.format('YYYY-MM-DD');
        // The real "today", independent of which day's note was edited — used
        // for anything that must stay anchored to the actual calendar (log
        // pruning, freeze-token refill), so backfilling an old note can never
        // wipe out or misdate today's own data. `dateStr` (the note's date)
        // still attributes XP/tasks/streak to the day the work was for.
        const todayStr = moment().format('YYYY-MM-DD');

        const levelBefore = calculateLevel(this.settings.gamificationTotalXP).level;

        let gainedXP = 0;
        let bestTier: RewardTier = 'normal';
        for (let i = 0; i < delta; i++) {
            const reward = rollReward(this.random);
            this.settings.gamificationTotalXP += reward.xp;
            gainedXP += reward.xp;
            if (tierRank(reward.tier) > tierRank(bestTier)) bestTier = reward.tier;
        }
        const levelAfter = calculateLevel(this.settings.gamificationTotalXP).level;
        const leveledUp = levelAfter > levelBefore;

        this.settings.gamificationTotalTasksCompleted += delta;
        if (!this.settings.gamificationStartDate) this.settings.gamificationStartDate = dateStr;
        this.settings.gamificationDailyXPLog[dateStr] = (this.settings.gamificationDailyXPLog[dateStr] ?? 0) + gainedXP;
        this.settings.gamificationDailyXPLog = pruneDailyXPLog(this.settings.gamificationDailyXPLog, todayStr);

        this.settings.gamificationDailyTaskLog[dateStr] = (this.settings.gamificationDailyTaskLog[dateStr] ?? 0) + delta;
        this.settings.gamificationDailyTaskLog = pruneDailyXPLog(this.settings.gamificationDailyTaskLog, todayStr);
        const todayTaskCount = this.settings.gamificationDailyTaskLog[dateStr];
        const newBestDayTasks = todayTaskCount > this.settings.gamificationBestDayTasks;
        if (newBestDayTasks) this.settings.gamificationBestDayTasks = todayTaskCount;

        const weekXP = sumRecentXP(this.settings.gamificationDailyXPLog, dateStr, 7);
        const newBestWeekXP = weekXP > this.settings.gamificationBestWeekXP;
        if (newBestWeekXP) this.settings.gamificationBestWeekXP = weekXP;

        const { newlyUnlocked, newBestStreak, isComeback, freezeMilestoneBonus } = this.updateStreakAndBadges(dateStr, todayStr);

        const specialUnlocks = checkNewlySpecialUnlocks(
            { hour: new Date().getHours(), todayTaskCount },
            this.settings.gamificationUnlockedBadges
        );
        if (specialUnlocks.length > 0) {
            this.settings.gamificationUnlockedBadges.push(...specialUnlocks.map((b) => b.id));
        }
        const allNewBadges = [...newlyUnlocked, ...specialUnlocks];

        // One status-bar moment per completion — pick the most exciting thing that happened.
        if (allNewBadges.length > 0) {
            this.flashBadge(allNewBadges[allNewBadges.length - 1]);
        } else if (leveledUp) {
            this.flashLevelUp(levelAfter);
        } else if (freezeMilestoneBonus > 0) {
            this.flash([{ icon: 'snowflake', text: `+${freezeMilestoneBonus} FREEZE` }], 2500);
        } else if (newBestStreak || newBestDayTasks || newBestWeekXP) {
            this.flashPersonalBest({ streak: newBestStreak, dayTasks: newBestDayTasks, weekXP: newBestWeekXP });
        } else if (isComeback) {
            this.flash([{ icon: 'leaf', text: `Best ${this.settings.gamificationBestStreak}d kept · fresh start` }], 2500);
        } else {
            this.flashReward({ xp: gainedXP, tier: bestTier });
        }
        this.refreshViews();
        // Debounced rather than awaited: checking off several tasks in a row
        // should coalesce into a single data.json write (and a single
        // updateSettings() cascade across every other service) instead of one
        // per checkbox. flushPendingSave() forces it out on unload.
        this.debouncedSave();
    }

    /**
     * Advance the streak (bridging a missed day with a freeze token if one is
     * available), refill freeze tokens on a new calendar month, grant
     * milestone freeze bonuses, track the best-ever streak, and unlock any
     * newly-earned badges.
     *
     * `activeDate` is the day the completed task belongs to (the daily
     * note's date); `today` is the real current date. Freeze-token refill
     * always uses `today`, since "this calendar month" is a real-time concept
     * that shouldn't shift just because an old note was edited.
     *
     * If `activeDate` is *earlier* than the last recorded active date, this
     * is a backfill (catching up on a stale, already-past daily note) rather
     * than today's activity — the streak, freeze tokens and last-active date
     * are left untouched so backfilling never resets progress that's already
     * been earned. XP/badges from the completion still apply regardless.
     */
    private updateStreakAndBadges(activeDate: string, today: string): StreakUpdateResult {
        const advance = resolveStreakAdvance({
            activeDate,
            today,
            previousActiveDate: this.settings.gamificationLastActiveDate || null,
            currentStreak: this.settings.gamificationStreak,
            freezeTokensAvailable: this.settings.gamificationFreezeTokensAvailable,
            freezeTokensRefillMonth: this.settings.gamificationFreezeTokensRefillMonth,
            bestStreak: this.settings.gamificationBestStreak,
            freezeMilestonesGranted: this.settings.gamificationFreezeMilestonesGranted,
            restDayOfWeek: this.settings.gamificationRestDayOfWeek,
        });

        this.settings.gamificationFreezeTokensAvailable = advance.freezeTokensAvailable;
        this.settings.gamificationFreezeTokensRefillMonth = advance.freezeTokensRefillMonth;
        this.settings.gamificationStreak = advance.streak;
        this.settings.gamificationLastActiveDate = advance.lastActiveDate;
        this.settings.gamificationBestStreak = advance.bestStreak;

        if (advance.freezeTokensUsed > 0) {
            this.settings.gamificationFreezeTokenLog.push(activeDate);
            this.settings.gamificationFreezeTokenLog = this.settings.gamificationFreezeTokenLog.slice(-10);
        }
        if (advance.newMilestones.length > 0) {
            this.settings.gamificationFreezeMilestonesGranted.push(...advance.newMilestones);
        }

        const state = {
            level: calculateLevel(this.settings.gamificationTotalXP).level,
            streak: this.settings.gamificationStreak,
            totalXP: this.settings.gamificationTotalXP,
        };
        const newlyUnlocked = checkNewlyUnlockedBadges(state, this.settings.gamificationUnlockedBadges);
        if (newlyUnlocked.length > 0) {
            this.settings.gamificationUnlockedBadges.push(...newlyUnlocked.map((b) => b.id));
        }

        return {
            newlyUnlocked,
            newBestStreak: advance.newBestStreak,
            isComeback: advance.isComeback,
            freezeMilestoneBonus: advance.newMilestones.length,
        };
    }

    getSnapshot(): GamificationSnapshot {
        const { level, xpIntoLevel, xpForNextLevel } = calculateLevel(this.settings.gamificationTotalXP);
        const badges: BadgeSnapshot[] = ALL_BADGES.map((badge) => ({
            ...badge,
            unlocked: this.settings.gamificationUnlockedBadges.includes(badge.id),
        }));
        const todayStr = moment().format('YYYY-MM-DD');
        return {
            enabled: this.settings.gamificationEnabled,
            level,
            levelTitle: titleForLevel(level),
            xpIntoLevel,
            xpForNextLevel,
            totalXP: this.settings.gamificationTotalXP,
            streak: this.settings.gamificationStreak,
            freezeTokensAvailable: this.settings.gamificationFreezeTokensAvailable,
            badges,
            todayProgress: this.todayProgress,
            totalTasksCompleted: this.settings.gamificationTotalTasksCompleted,
            startDate: this.settings.gamificationStartDate || null,
            weeklyXP: getWeeklyXPSeries(this.settings.gamificationDailyXPLog, todayStr, 7),
            monthlyXP: getWeeklyXPSeries(this.settings.gamificationDailyXPLog, todayStr, 30),
            nearestBadge: findNearestBadgeTarget(
                { level, streak: this.settings.gamificationStreak },
                this.settings.gamificationUnlockedBadges
            ),
            freezeTokenLog: this.settings.gamificationFreezeTokenLog,
            bestStreak: this.settings.gamificationBestStreak,
            bestDayTasks: this.settings.gamificationBestDayTasks,
            bestWeekXP: this.settings.gamificationBestWeekXP,
        };
    }

    private refreshViews() {
        for (const leaf of this.app.workspace.getLeavesOfType(VIEW_TYPE_GAMIFICATION)) {
            const view = leaf.view as unknown as { refresh?: () => void };
            view.refresh?.();
        }
    }

    private renderStatusBar() {
        if (!this.statusBarItem) return;
        if (!this.settings.gamificationEnabled) {
            this.statusBarItem.empty();
            this.statusBarItem.style.display = 'none';
            return;
        }
        this.statusBarItem.style.display = '';
        const { level, xpIntoLevel, xpForNextLevel } = calculateLevel(this.settings.gamificationTotalXP);
        this.setStatusBarContent([
            { icon: 'zap', text: `Lv${level}` },
            { text: `${xpIntoLevel}/${xpForNextLevel}` },
            { icon: 'flame', text: `${this.settings.gamificationStreak}` },
            { icon: 'snowflake', text: `${this.settings.gamificationFreezeTokensAvailable}` },
        ]);
    }

    /** Render icon+text segments into the status bar, separated by a middle dot. */
    private setStatusBarContent(segments: StatusSegment[]) {
        const bar = this.statusBarItem;
        if (!bar) return;
        bar.empty();
        segments.forEach((segment, index) => {
            if (index > 0) bar.createSpan({ cls: 'crystal-gv-sep', text: '·' });
            if (segment.icon) {
                const iconEl = bar.createSpan({ cls: 'crystal-gv-status-icon' });
                setIcon(iconEl, segment.icon);
            }
            bar.createSpan({ text: segment.text });
        });
    }

    /**
     * Briefly replace the status bar content with the reward just earned, then
     * fall back to the normal Lv/XP/streak display. No popup — the payoff
     * lives entirely in the status bar so it never interrupts the editor.
     */
    private flashReward(reward: Reward) {
        const icon = reward.tier === 'rare' ? 'gem' : reward.tier === 'bonus' ? 'sparkles' : 'zap';
        this.flash([{ icon, text: `+${reward.xp} XP` }], 1500);
    }

    /** Same idea as `flashReward`, but for a newly unlocked badge (shown longer). */
    private flashBadge(badge: Badge) {
        this.flash([{ icon: 'award', text: 'NEW' }, { icon: badge.icon, text: badge.name }], 2500);
    }

    /** A level-up is the headline event of the whole XP system — it gets its
     * own moment instead of blending into a routine XP-reward flash. */
    private flashLevelUp(level: number) {
        this.flash([{ icon: 'trending-up', text: 'LEVEL UP' }, { icon: 'zap', text: `Lv${level}` }], 2500);
    }

    /** Celebrates beating a personal record — translates SNS-style "compare to others" into "compare to your past self". */
    private flashPersonalBest(broke: { streak: boolean; dayTasks: boolean; weekXP: boolean }) {
        const text = broke.streak ? `${this.settings.gamificationBestStreak}d streak`
            : broke.dayTasks ? `${this.settings.gamificationBestDayTasks}/day`
                : `${this.settings.gamificationBestWeekXP} XP/wk`;
        this.flash([{ icon: 'trophy', text: 'BEST' }, { text }], 2200);
    }

    private flash(segments: StatusSegment[], duration: number) {
        if (!this.statusBarItem || !this.settings.gamificationEnabled) return;

        this.setStatusBarContent(segments);
        this.statusBarItem.addClass('crystal-gamification-status--flash');

        if (this.flashTimeoutId !== null) {
            window.clearTimeout(this.flashTimeoutId);
        }
        this.flashTimeoutId = window.setTimeout(() => {
            this.statusBarItem?.removeClass('crystal-gamification-status--flash');
            this.flashTimeoutId = null;
            this.renderStatusBar();
        }, duration);
        this.plugin.registerInterval(this.flashTimeoutId);
    }

    /**
     * Persist settings after a short debounce window so rapid-fire checkbox
     * toggles (checking off several tasks at once) coalesce into a single
     * data.json write — and a single `updateSettings()` cascade across every
     * other service — instead of one per task.
     */
    private debouncedSave() {
        if (this.saveDebounceId !== null) {
            window.clearTimeout(this.saveDebounceId);
        }
        this.saveDebounceId = window.setTimeout(() => {
            this.saveDebounceId = null;
            this.plugin.saveSettings().catch((error) => {
                console.error('Crystal gamification: failed to save settings', error);
            });
        }, 400);
        this.plugin.registerInterval(this.saveDebounceId);
    }

    /**
     * Force out any pending debounced save immediately. Called on plugin
     * unload so a completion right before Obsidian closes/reloads doesn't
     * get lost in the debounce window.
     */
    flushPendingSave() {
        if (this.saveDebounceId === null) return;
        window.clearTimeout(this.saveDebounceId);
        this.saveDebounceId = null;
        this.plugin.saveSettings().catch((error) => {
            console.error('Crystal gamification: failed to save settings', error);
        });
    }
}

interface StatusSegment {
    icon?: string;
    text: string;
}

function tierRank(tier: RewardTier): number {
    return tier === 'rare' ? 2 : tier === 'bonus' ? 1 : 0;
}
